# Generated by Django 4.2.4 on 2023-08-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=20)),
                ('giro', models.CharField(blank=True, max_length=100)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('correo_electronico', models.CharField(blank=True, max_length=100)),
                ('tipo_cliente', models.CharField(choices=[('Freight broker', 'Freight broker'), ('Owner operator', 'Owner operator'), ('Warehousing', 'Warehousing'), ('US Custom broker', 'US Custom broker'), ('Agente aduanal', 'Agente aduanal'), ('Lineas de transporte', 'Lineas de transporte')], max_length=30)),
                ('tipo_mercancia', models.CharField(choices=[('Perecedero', 'Perecedero'), ('Industrial', 'Industrial')], max_length=30)),
                ('cantidad_de_viajes', models.CharField(max_length=30)),
                ('northbound', models.BooleanField(default=False)),
                ('southbound', models.BooleanField(default=False)),
                ('ctpat', models.BooleanField(default=False)),
                ('nombre_contacto', models.CharField(blank=True, max_length=100)),
                ('telefono_contacto', models.CharField(blank=True, max_length=100)),
                ('correo_contacto', models.CharField(blank=True, max_length=100)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('calle', models.CharField(blank=True, max_length=100)),
                ('numero', models.CharField(blank=True, max_length=100)),
                ('colonia', models.CharField(blank=True, max_length=100)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=100)),
                ('pais', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
